name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint files
        run: yarn lint

      - name: Typecheck files
        run: yarn typecheck

  test:
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Start Metro Bundler
        continue-on-error: true
        working-directory: ./example
        run: nohup sh -c "yarn start > metro.log 2>&1 &"

      - name: Run unit tests
        working-directory: ./example
        # TODO nyc breaks xcodebuild
        # run: jet --target=macos --coverage
        run: |
          cd macos
          pod install
          cd ..
          npx jet --target=macos

      - name: Upload Metro Log
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: metro_log
          path: example/metro.log

  build-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: yarn build
